Repository rmfpdlxmtidl/sobok, pull requests merged in 2021-08, with the labels that each got.

#2 Fix/#1/load favicon file
  CONTRIBUTING.md
  public/favicon.ico
  public/images/iphoneplus_splash.png
  public/images/iphonex_splash.png
  public/images/og-image.webp
  public/images/sobok-logo-144.webp
  public/images/sobok-logo-192.webp
  public/images/sobok-logo-512.webp
  public/manifest.json
  src/components/layouts/PageHead.tsx
  src/pages/_document.tsx
Labels: bug

#5 Develop
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_development.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📖 documentation

#7 Feature/#6/connect graphql api
  .github/ISSUE_TEMPLATE/feature_development.md
  src/components/atoms/Styles.ts
  src/graphql/generated/types-and-hooks.ts
  src/graphql/queries/IsEmailUnique.graphql
  src/graphql/queries/IsIdUnique.graphql
  src/pages/index.tsx
  src/pages/register.tsx
Labels: ☁️ new feature

#28 Feature/#23/bottom navigation
  public/images/bucket-color.svg
  public/images/bucket.svg
  public/images/home-color.svg
  public/images/home.svg
  public/images/my-color.svg
  public/images/my.svg
  public/images/sobok-logo.svg
  src/components/TopHeader.tsx
  src/components/atoms/SVGs.tsx
  src/layouts/HomeLayout.tsx
  src/layouts/NavigationLayout.tsx
  src/models/constants.ts
  src/pages/[userId]/buckets/[name].tsx
  src/pages/[userId]/buckets/index.tsx
  src/pages/[userId]/index.tsx
  src/pages/news/all.tsx
  src/pages/news/index.tsx
  src/pages/trends/[id].tsx
  src/pages/trends/index.tsx
Labels: ☁️ new feature

#26 Develop
  .github/ISSUE_TEMPLATE/feature_development.md
  .yarnrc.yml
  package.json
  public/images/arrow-down.svg
  public/images/bucket-color.svg
  public/images/bucket.svg
  public/images/home-color.svg
  public/images/home.svg
  public/images/map.svg
  public/images/my-color.svg
  public/images/my.svg
  public/images/search.svg
  public/images/sobok-logo.svg
  src/components/StoreMenuCard.tsx
  src/components/atoms/ClientSideLink.tsx
  src/components/atoms/SVGs.tsx
  src/components/atoms/Styles.ts
  src/graphql/generated/types-and-hooks.ts
  src/graphql/queries/StoreMenu.graphql
  src/layouts/HomeLayout.tsx
  src/layouts/NavigationLayout.tsx
  src/models/constants.ts
  src/pages/[userId]/buckets/[name].tsx
  src/pages/[userId]/buckets/index.tsx
  src/pages/[userId]/index.tsx
  src/pages/feed/index.tsx
  src/pages/index.tsx
  src/pages/menus.tsx
  src/pages/news/all.tsx
  src/pages/news/index.tsx
  src/pages/stores/[id]/[menuName].tsx
  src/pages/stores/[id]/feed.tsx
  src/pages/stores/[id]/index.tsx
  src/pages/stores/[id]/info.tsx
  src/pages/stores/[id]/news.tsx
  src/pages/trends/[id].tsx
  src/pages/trends/index.tsx
  src/styles/custom-antd.css
  yarn.lock
Labels: 🧪 test

#36 feature/#22/category
  public/images/carousel.webp
  public/images/carousel@2x.webp
  public/images/carousel@3x.webp
  public/images/categories/all.min.svg
  public/images/categories/outlet.min.svg
  public/images/categories/park.min.svg
  public/images/categories/pet.min.svg
  public/images/categories/table.min.svg
  src/components/Category.tsx
  src/layouts/HomeLayout.tsx
  src/layouts/NavigationLayout.tsx
  src/pages/index.tsx
Labels: ☁️ new feature

#44 Fix image name error
  src/components/Category.tsx
Labels: 🐛 bug
